name: "Endor Labs Scan"
description: "Endor Labs repository scan"
author: "Endor Labs"
inputs:
  # Use this input parameter to define your Endor Labs tenant namespace 
  endor_namespace:
    description: "The Endor Labs namespace"
    required: true
  # Use this input parameter to define if you want to show a scan progress bar
  # In some environments this can fill up your log
  endor_show_progress:
    description: "Set to true to show the progress bar for scans"
    default: "false"
  endor_log_verbose:
    description: "Set to true to use verbose logging"
    default: "false"
  # Set log level to debug for error troubleshooting
  endor_log_level:
    description: "Set the endorctl log level"
    default: "info"
  endor_scan_summary_output_type:
    description: "Set the desired output summary to table, json, or yaml"
    default: "table"
  endor_source_path:
    description: "Set the source code path to scan. Used to define custom checkout paths"
    default: "/github/workspace"
  # Custom arguments to the endorctl binary. See the documentation for command flags.
  endor_additional_args:
    description: "Use this to add your own custom arguments to endorctl"
runs:
  using: "docker"
  image: "docker://us-central1-docker.pkg.dev/endor-ci/public/endorctl:v0.5.64"
  args:
  - scan
  - --namespace=${{ inputs.endor_namespace }}
  - --show-progress=${{ inputs.endor_show_progress }}
  - --verbose=${{ inputs.endor_log_verbose }}
  - --log-level=${{ inputs.endor_log_level }}
  - --output-type=${{ inputs.endor_scan_summary_output_type }}
  - --path=${{ inputs.endor_source_path }}
  - ${{ inputs.endor_additional_args }}
