name: Scan with Endor Labs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  endor-scan:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Compile Package
        run: mvn clean install -Dskiptests
      - name: Run endorctl to scan a pull request.
        uses: endorlabs/actions@main
        with:
          api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          # gcp_service_account: ${{ secrets.CI_SERVICE_ACCOUNT }}
          namespace: "demo"
        env:
          # Set to false on create tag to specify a tracked release version of your code. This is done on create events by default to specify a release.
          ENDOR_CI_RUN: "true" # Should generally be set to true for pull requests. 
          # Set ENDOR_CI_RUN_TAGS to searchable parameters to be used in the Endor Labs API and user interface.
          ENDOR_CI_RUN_TAGS: Actor:${{ github.actor }},Run_ID:${{ github.run_id	}},Run_Number:${{ github.run_id	}},Ref:${{ github.ref	}}
        if: github.event_name == 'pull_request' 
      - name: Scan a push to the default branch
        uses: endorlabs/actions@main
        with:
          api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          # gcp_service_account: ${{ secrets.CI_SERVICE_ACCOUNT }}
          namespace: "demo"
        env:
          ENDOR_CI_RUN: "false"
        if: github.event_name == 'push'
      - name: Run endorctl to scan a release tag
        uses: endorlabs/actions@main
        with:
          api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          # gcp_service_account: ${{ secrets.CI_SERVICE_ACCOUNT }}
          namespace: "demo"
        env:
          # Set to false on create tag to specify a tracked release version of your code. This is done on tags by default to specify a release.
          ENDOR_CI_RUN: "false"
          #
          # Use CI Run Tags as search parameters if you'd like to review CI Scan Results in Endor Labs.
          #
          ENDOR_CI_RUN_TAGS: Actor:${{ github.actor }},Run_ID:${{ github.run_id	}},Run_Number:${{ github.run_id	}},Ref:${{ github.ref	}}
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
