name: Endor Labs Scan
on:
  push:
    branches: [ main ]
jobs:
  ci-commons-demo-scan:
    permissions:
      id-token: write
      contents: read # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Compile Package
        run: mvn clean install
      - uses: endorlabs/github-action@main
        with:
          namespace: demo-playground
          scan_summary_output_type: "table"
          ci_run: "false"
          enable_github_action_token: "true"
          additional_args: "--enable=git,github,analytics"
