name: Endor Labs Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    permissions:
      security-events: write # Used to upload sarif artifact to GitHub
      contents: read # Used to checkout a private repository but actions/checkout. 
      actions: read # Required for private repositories to upload sarif files. GitHub Advanced Security licenses are required.
      id-token: write # Used for keyless authentication to Endor Labs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Build Package
      run: mvn clean install -Dcheckstyle.skip=true -Djacoco.skip=true -Dmaven.test.skip=true -DskipSource=true -DskipTests=true -Dcobertura.skip=true -Dduplicate-finder.skip=true -Denforcer.skip=true -Dlicense.skipAddThirdParty=true -Dgpg.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true -Dlicense.skip=true
    - name: Endor Labs Scan Pull Request
      if: github.event_name == 'pull_request'
      uses: endorlabs/github-action@main
      with:
        namespace: "demo"
        scan_summary_output_type: "table"
        ci_run: "true"
        sarif_file: findings.sarif
    - name: Endor Labs Scan Push to main
      if: github.event_name == 'push'
      uses: endorlabs/github-action@main
      with:
        namespace: "demo"
        api: "https://api.staging.endorlabs.com"
        scan_summary_output_type: "table"
        ci_run: "false"
        sarif_file: findings.sarif
    - name: Upload SARIF to github
      uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd
      with:
        sarif_file: findings.sarif
