name: Scan with Endor Labs
on:
  pull_request:
  push:
  create:
    type: tag
jobs:
  endor-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run endorctl to scan a CI run
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: endorlabs/ci-commons-text-demo@main
        with:
          endor_namespace: "demo"
        env:
          # Use the environment variables ENDOR_API_CREDENTIALS_KEY and ENDOR_API_CREDENTIALS_SECRET
          # to authenticate to Endor Labs using an API Key. If you are using keyless authentication remove this.
          ENDOR_API_CREDENTIALS_KEY: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          ENDOR_API_CREDENTIALS_SECRET: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          # Set to false on create tag to specify a tracked release version of your code
          ENDOR_CI_RUN: "true" 
          # ENDOR_CI_RUN_TAGS: "
          #
          # Uncomment the below environment variable to enable keyless authentication with GCP
          # remove the environment variables ENDOR_API_CREDENTIALS_KEY and ENDOR_API_CREDENTIALS_SECRET when using.
          #
          # ENDOR_GCP_CREDENTIALS_SERVICE_ACCOUNT: "endorlabs-federation@<insert-your-project>.iam.gserviceaccount.com"
      - name: Run endorctl to scan a CI run
        if: github.event_name == "push" || github.event_name == "pull_request"
        uses: endorlabs/ci-commons-text-demo@main
        with:
          endor_namespace: "demo"
        env:
          # Use the environment variables ENDOR_API_CREDENTIALS_KEY and ENDOR_API_CREDENTIALS_SECRET
          # to authenticate to Endor Labs using an API Key. If you are using keyless authentication remove this.
          ENDOR_API_CREDENTIALS_KEY: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          ENDOR_API_CREDENTIALS_SECRET: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          # Set to false on create tag to specify a tracked release version of your code
          ENDOR_CI_RUN: "true" 
          # ENDOR_CI_RUN_TAGS: "
          #
          # Uncomment the below environment variable to enable keyless authentication with GCP
          # remove the environment variables ENDOR_API_CREDENTIALS_KEY and ENDOR_API_CREDENTIALS_SECRET when using.
          #
          # ENDOR_GCP_CREDENTIALS_SERVICE_ACCOUNT: "endorlabs-federation@<insert-your-project>.iam.gserviceaccount.com"
      - name: Run endorctl to scan a release tag
        if: github.event_name == "create" 
        uses: endorlabs/ci-commons-text-demo@main
        with:
          endor_namespace: "demo"
        env:
          # Use the environment variables ENDOR_API_CREDENTIALS_KEY and ENDOR_API_CREDENTIALS_SECRET
          # to authenticate to Endor Labs using an API Key. If you are using keyless authentication remove this.
          ENDOR_API_CREDENTIALS_KEY: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          ENDOR_API_CREDENTIALS_SECRET: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          # Set to false on create tag to specify a tracked release version of your code
          ENDOR_CI_RUN: "false" 
          # Uncomment the below environment variable to enable keyless authentication with GCP
          # remove the environment variables ENDOR_API_CREDENTIALS_KEY and ENDOR_API_CREDENTIALS_SECRET when using.
          #
          # ENDOR_GCP_CREDENTIALS_SERVICE_ACCOUNT: "endorlabs-federation@<insert-your-project>.iam.gserviceaccount.com"
