name: Endor Labs Example
on: push
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan with Endor Labs
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Scan with Endor Labs
        uses: endorlabs/github-action@main
        with:
          api_key: ${{ secrets.ENDOR_API_KEY }}
          api_secret: ${{ secrets.ENDOR_API_SECRET }}
          namespace: "demo"
